package modelo;
// Generated 23/06/2021 11:46:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Autobus generated by hbm2java
 */
public class Autobus  implements java.io.Serializable {


     private Integer id;
     private Conductor conductor;
     private String marca;
     private String modelo;
     private String color;
     private Set<Boleto> boletos = new HashSet<Boleto>(0);

    public Autobus() {
    }

	
    public Autobus(Conductor conductor, String marca, String modelo, String color) {
        this.conductor = conductor;
        this.marca = marca;
        this.modelo = modelo;
        this.color = color;
    }
    public Autobus(Conductor conductor, String marca, String modelo, String color, Set<Boleto> boletos) {
       this.conductor = conductor;
       this.marca = marca;
       this.modelo = modelo;
       this.color = color;
       this.boletos = boletos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set<Boleto> getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set<Boleto> boletos) {
        this.boletos = boletos;
    }




}


