package modelo;
// Generated 23/06/2021 11:46:29 PM by Hibernate Tools 4.3.1



/**
 * Boleto generated by hbm2java
 */
public class Boleto  implements java.io.Serializable {


     private Integer id;
     private Autobus autobus;
     private Pasajero pasajero;
     private String origen;
     private String destino;
     private String fechaSalida;
     private int precio;

    public Boleto() {
    }

    public Boleto(Autobus autobus, Pasajero pasajero, String origen, String destino, String fechaSalida, int precio) {
       this.autobus = autobus;
       this.pasajero = pasajero;
       this.origen = origen;
       this.destino = destino;
       this.fechaSalida = fechaSalida;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Autobus getAutobus() {
        return this.autobus;
    }
    
    public void setAutobus(Autobus autobus) {
        this.autobus = autobus;
    }
    public Pasajero getPasajero() {
        return this.pasajero;
    }
    
    public void setPasajero(Pasajero pasajero) {
        this.pasajero = pasajero;
    }
    public String getOrigen() {
        return this.origen;
    }
    
    public void setOrigen(String origen) {
        this.origen = origen;
    }
    public String getDestino() {
        return this.destino;
    }
    
    public void setDestino(String destino) {
        this.destino = destino;
    }
    public String getFechaSalida() {
        return this.fechaSalida;
    }
    
    public void setFechaSalida(String fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }




}


