package modelo;
// Generated 23/06/2021 11:46:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String tipoLicencia;
     private String nacionalidad;
     private Set<Autobus> autobuses = new HashSet<Autobus>(0);

    public Conductor() {
    }

	
    public Conductor(String nombre, String apaterno, String amaterno, String tipoLicencia, String nacionalidad) {
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.tipoLicencia = tipoLicencia;
        this.nacionalidad = nacionalidad;
    }
    public Conductor(String nombre, String apaterno, String amaterno, String tipoLicencia, String nacionalidad, Set<Autobus> autobuses) {
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.tipoLicencia = tipoLicencia;
       this.nacionalidad = nacionalidad;
       this.autobuses = autobuses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getTipoLicencia() {
        return this.tipoLicencia;
    }
    
    public void setTipoLicencia(String tipoLicencia) {
        this.tipoLicencia = tipoLicencia;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Set<Autobus> getAutobuses() {
        return this.autobuses;
    }
    
    public void setAutobuses(Set<Autobus> autobuses) {
        this.autobuses = autobuses;
    }




}


