package modelo;
// Generated 23/06/2021 11:46:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pasajero generated by hbm2java
 */
public class Pasajero  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String nacionalidad;
     private Set<Boleto> boletos = new HashSet<Boleto>(0);

    public Pasajero() {
    }

	
    public Pasajero(String nombre, String apaterno, String amaterno, String nacionalidad) {
        this.nombre = nombre;
        this.apaterno = apaterno;
        this.amaterno = amaterno;
        this.nacionalidad = nacionalidad;
    }
    public Pasajero(String nombre, String apaterno, String amaterno, String nacionalidad, Set<Boleto> boletos) {
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.nacionalidad = nacionalidad;
       this.boletos = boletos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public Set<Boleto> getBoletos() {
        return this.boletos;
    }
    
    public void setBoletos(Set<Boleto> boletos) {
        this.boletos = boletos;
    }




}


